project:
  type: website
  output-dir: docs

website:
  title: "Naomi Howard"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Diving.qmd
      - EnvironmentalProjects.qmd 
      page-footer:
      background: light
      left: Copyright 2024, Naomi Howard
      right:
        icon: github
        href: https://github.com/naomihoward11
format:
  html:
    theme: lumen
    css: styles.css
    
    toc: true
    
    page-layout: full

editor: visual

