project:
  type: website
  output-dir: docs

website:
  title: "Naomi Howard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Diving.qmd
      - EnvironmentalProjects.qmd 
    page-footer:
      background: light # or `dark`
      left: Copyright 2024, Naomi Howard
      right: 
      icon: github
      text: https://github.com/naomihoward11
    
    
format:
  html:
    custom_html_header: |
      <style>
        /* CSS styles for the document */
        :root {
          --primary-color: #ffb6c1; /* Light pink */
          --secondary-color: #ffc0cb; /* Pink */
          --background-color: #fff0f5; /* Lavender blush */
          /* Add more CSS styles as needed */
        }
      </style>
    theme: morph
    css: styles.css
    toc: true
    page-layout: full

    

editor: visual

